[rocksdb]
path = "./tmp"

[api]
ip = "127.0.0.1"
port = 3000

[bitcoin_rpc]
rpc_url = "http://anoa.io:8332"
rpc_user = "admin"
rpc_password = "admin"

[indexer]
log_interval = 10
mem_alloc_pubkey_hset = 1024